@local = http://localhost:3001

### health-check
GET {{local}}/

### Ip proxy check
GET {{local}}/ip

### timeout
GET {{local}}/timeout

### error
GET {{local}}/error

### angler by id
GET {{local}}/angler/sample_x

### angler not found
GET {{local}}/angler/invalid

### catch-all
GET {{local}}/idk

### new fish
GET {{local}}/fish

### catch fish
PUT {{local}}/fish
Content-Type: application/json

{
  "fishId": "2W7Wyim2MoYjcDWVqu5O",
  "anglerId": "sample_z"
}

### delete fish by id
DELETE {{local}}/fish
Content-Type: application/json

{
  "id": "9GI0P39CqBOnfRLXRq9m"
}

### create new angler
POST {{local}}/angler
Content-Type: application/json

{
  "id": "sample_z",
  "name": "zillion",
  "boat": "aluminum",
  "rod": "bamboo",
  "reel": "spinning",
  "bait": "jerkbait"
}

### update angler
PUT {{local}}/angler
Content-Type: application/json

{
  "id": "sample_z",
  "name": "trillion",
  "reel": "spincast",
}